### ISSUE TITLE
getVisibleTodos() will trigger unwanted react component updates

### ISSUE THREAD

**Issue by andrei-cacio** [gaearon/todos#16]
Correct me if I'm wrong but, based on [VisibleTodoList](https://github.com/gaearon/todos/blob/20-splitting-the-reducer-files/src/components/VisibleTodoList.js#L44)'s `mapStateToProps`, won't this kind of thing trigger component rerenders for every `dispatch()`ed action in the app? Because the function returns a new array everytime so shallow comparing it won't work for pure components.

Shouldn't these kind of patterns be avoided? @gaearon

**Comment by andrwsalcdo** [comment]
@andrei-cacio Yes, you are right. 

I don't know if you already found the answer you were looking for, but here you go, just in case. :D 

The Reselect library talks about this example as a motivation to create memoized selectors. 
[Motivation for Memoized Selectors](https://github.com/reactjs/reselect#motivation-for-memoized-selectors)

**Comment by Splintex** [comment]
@andrei-cacio Do u want to create pull request with reselect? Or I can do that.

**Comment by gaearon** [comment]
Can't teach everything in one course. Yes, in real apps you'll probably want to use memoization once this becomes a perf problem. This is explained right on Redux website so after the course you should have enough information to be able to read it: http://redux.js.org/docs/recipes/ComputingDerivedData.html
